name: run-regression-tests

on: push
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout the eclipse plugin repository.
      - name: 'Setup: Checkout plugin'
        uses: actions/checkout@v2

      # Install Software.
      - name: 'Setup: Install required software' 
        run: ./tests/resources/ci/scripts/setup.sh
        
      # Build the plugin.
      - name: 'Build: Build-Package-RunTests'
        run: \
          ./tests/resources/ci/scripts/exec.sh